matrix:
- name: Markdown
  aspell:
    lang: ru
    ignore-case: true
  dictionary:
    wordlists:
    - config/spellcheck/.wordlist.txt
    encoding: utf-8
    output: build/dictionary/dictionary.dic
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
        - pymdownx.superfences:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - :matches(code, pre)
  sources:
  - 'lab*/*.md'
  - '*.md'
  - 'docs/**/*_ru.md'
  default_encoding: utf-8

- name: Markdown (English docs)
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - config/spellcheck/.wordlist_en.txt
    encoding: utf-8
    output: build/dictionary/dictionary_en.dic
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
        - pymdownx.superfences:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - :matches(code, pre)
  sources:
  - 'docs/**/*[^(_ru)].md'
  default_encoding: utf-8
