[tool.pytest.ini_options]
markers = [
    "mark4: tests for level 4",
    "mark6: tests for level 6",
    "mark8: tests for level 8",
    "mark10: tests for level 10",
    "lab_1_keywords_tfidf: lab_1_keywords_tfidf",
    "lab_2_keywords_cooccurrence: lab_2_keywords_cooccurrence"
]
norecursedirs = [
    "venv*"
]

[tool.coverage.run]
omit = [
    '*/tests/*'
]

[tool.mypy]
python_version = 3.9
exclude = [
    'venv*',
    'tests/'
]

disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

# simplifications
disable_error_code = [
    'var-annotated',
    'union-attr',

    # needed for seminars, to this moment not fixed: https://github.com/python/mypy/issues/9440
    'attr-defined'
]

[[tool.mypy.overrides]]
module = 'memory_profiler'
ignore_missing_imports = true

[tool.black]
line-length = 120
target-version = ['py39']
