name: "Update PR Fork on PR Comment"
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  sync:

    name: Update PR Fork on PR Comment
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/update')
    runs-on: ubuntu-latest

    steps:
      - name: Fetch remote URL
        id: fetch_remote_url
        uses: actions/github-script@v6
        with:
          script: |
            const { issue, repository } = context.payload;
            const [ owner, repo ] = repository.full_name.split('/');
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: issue.number
            });
            const { clone_url: prRemoteUrl } = pullRequest.head.repo;
            core.setOutput('pr_remote_url', prRemoteUrl)
      - uses: actions/checkout@v2
      - name: Merge upstream
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        id: update
        run: |
          # Determine what strategy should be used
          STRATEGY=get_new
          COMMENT="${{ github.event.comment.body }}"
          if [[ "${COMMENT}" == *"get_new"* ]]; then
            STRATEGY=get_new
          elif [[ "${COMMENT}" == *"keep_upstream"* ]]; then
            STRATEGY=keep_upstream
          elif [[ "${COMMENT}" == *"keep_fork"* ]]; then
            STRATEGY=keep_fork
          fi
          bash config/github/update_fork.sh --URL ${{ steps.fetch_remote_url.outputs.pr_remote_url }} --USER WhiteJaeger --STRATEGY $STRATEGY --AUTH "$AUTH_TOKEN"
      - name: Report on update
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Branch was updated!
              Changed files: \`${{ steps.update.outputs.files_diff }}\``
            })
